### ISSUE TITLE
When I run python blink/build_faiss_index.py --output_path models/faiss_flat_index.pkl

### ISSUE THREAD

**Issue by saswatidana** [facebookresearch/BLINK#39]
I get an error Traceback (most recent call last):
File "blink/build_faiss_index.py", line 14, in
from blink.indexer.faiss_indexer import DenseFlatIndexer, DenseHNSWFlatIndexer
ModuleNotFoundError: No module named 'blink.indexer'

Then I changed the line 14, with "index" instead of indexer.

After that I get the below error

python blink/build_faiss_index.py --output_path models/faiss_flat_index.pkl
10/14/2020 03:02:33 - INFO - Blink - Loading candidate encoding from path: /private/home/ledell/BLINK-Internal/models/all_entities_large.t7
Traceback (most recent call last):
File "blink/build_faiss_index.py", line 74, in
main(params)
File "blink/build_faiss_index.py", line 26, in main
candidate_encoding = torch.load(params["candidate_encoding"])
File "/dccstor/sasdana27/el4qa/lib/python3.7/site-packages/torch/serialization.py", line 381, in load
f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/private/home/ledell/BLINK-Internal/models/all_entities_large.t7'

Looks like some path issue. I have the file 'all_entities_large.t7' in BLINK/models/

**Comment by saswatidana** [comment]
I get an error Traceback (most recent call last):
  File "blink/build_faiss_index.py", line 14, in <module>
    from blink.indexer.faiss_indexer import DenseFlatIndexer, DenseHNSWFlatIndexer
ModuleNotFoundError: No module named 'blink.indexer'


Then I changed the line 14, with "index" instead of indexer.

After that I get the below error

python blink/build_faiss_index.py --output_path models/faiss_flat_index.pkl
10/14/2020 03:02:33 - INFO - Blink -   Loading candidate encoding from path: /private/home/ledell/BLINK-Internal/models/all_entities_large.t7
Traceback (most recent call last):
  File "blink/build_faiss_index.py", line 74, in <module>
    main(params)
  File "blink/build_faiss_index.py", line 26, in main
    candidate_encoding = torch.load(params["candidate_encoding"])
  File "/dccstor/sasdana27/el4qa/lib/python3.7/site-packages/torch/serialization.py", line 381, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/private/home/ledell/BLINK-Internal/models/all_entities_large.t7'
