### ISSUE TITLE
Flair version is old

### ISSUE THREAD

**Issue by HelloRusk** [facebookresearch/BLINK#41]
It looks like Flair v0.4.3 is not working, due to the broken link in which they store the embeddings.

https://github.com/flairNLP/flair/issues/1831

This problem prevents BLINK from being used interactively. I guess Flair v0.6.1 solves this bug, but upgrading may badly affect other libraries BLINK depends on...

**Comment by lamchiminhmark** [comment]
I am also running into this prooblem. Updating Flair to the latest version 0.6.1, and then running `python blink/main_dense.py -i --fast` gives the following error:
```
Traceback (most recent call last):
  File "blink/main_dense.py", line 18, in <module>
    import blink.ner as NER
  File "/Users/minhlam/BLINK/blink/ner.py", line 7, in <module>
    from flair.models import SequenceTagger
  File "/Users/minhlam/opt/miniconda3/envs/blink37/lib/python3.7/site-packages/flair/__init__.py", line 21, in <module>
    from . import trainers
  File "/Users/minhlam/opt/miniconda3/envs/blink37/lib/python3.7/site-packages/flair/trainers/__init__.py", line 1, in <module>
    from .trainer import ModelTrainer
  File "/Users/minhlam/opt/miniconda3/envs/blink37/lib/python3.7/site-packages/flair/trainers/trainer.py", line 33, in <module>
    from torch.optim.lr_scheduler import OneCycleLR
ImportError: cannot import name 'OneCycleLR' from 'torch.optim.lr_scheduler' (/Users/minhlam/opt/miniconda3/envs/blink37/lib/python3.7/site-packages/torch/optim/lr_scheduler.py)
```
Is there any update on this yet?

**Comment by shellshock1911** [comment]
I've tested most of the BLINK codebase with the latest versions of all the dependencies in the `requirements.txt`, including PyTorch 1.6.0 and Flair 0.6.1, so I would recommend making an environment with the latest upgrades, and try running it again. Don't worry about the exact versions in `requirements.txt`.

**Comment by HelloRusk** [comment]
I'm also in favor of upgrading PyTorch version. It worked fine for me too.
