### ISSUE TITLE
ImportError: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE

### ISSUE THREAD

**Issue by Jun-jie-Huang** [facebookresearch/BLINK#87]
# ❓ Questions and Help

Hi, I'm running BLINK with the following command `PYTHONPATH=. python blink/main_dense.py -i` , but it raises an ImportError.
```
I0613 10:22:33.557159 139884357551936 modeling_utils.py:533] loading weights file https://s3.amazonaws.com/models.huggingface.co/bert/bert-large-uncased-pytorch_model.bin from cache at /home/t-jhuang/.cache/torch/pytorch_transformers/54da47087cc86ce75324e4dc9bbb5f66c6e83a7c6bd23baea8b489acc8d09aa4.4d5343a4b979c4beeaadef17a0453d1bb183dd9b084f58b84c7cc781df343ae6
Traceback (most recent call last):
  File "blink/main_dense.py", line 692, in <module>
    models = load_models(args, logger)
  File "blink/main_dense.py", line 297, in load_models
    biencoder = load_biencoder(biencoder_params)
  File "/vc_data/users/t-jhuang/BLINK/blink/biencoder/biencoder.py", line 28, in load_biencoder
    biencoder = BiEncoderRanker(params)
  File "/vc_data/users/t-jhuang/BLINK/blink/biencoder/biencoder.py", line 89, in __init__
    self.build_model()
  File "/vc_data/users/t-jhuang/BLINK/blink/biencoder/biencoder.py", line 107, in build_model
    self.model = BiEncoderModule(self.params)
  File "/vc_data/users/t-jhuang/BLINK/blink/biencoder/biencoder.py", line 35, in __init__
    ctxt_bert = BertModel.from_pretrained(params["bert_model"])
  File "/usr/local/lib/python3.6/dist-packages/pytorch_transformers/modeling_utils.py", line 536, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_transformers/modeling_bert.py", line 651, in __init__
    self.embeddings = BertEmbeddings(config)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_transformers/modeling_bert.py", line 240, in __init__
    self.LayerNorm = BertLayerNorm(config.hidden_size, eps=config.layer_norm_eps)
  File "/home/t-jhuang/.local/lib/python3.6/site-packages/apex/normalization/fused_layer_norm.py", line 133, in __init__
    fused_layer_norm_cuda = importlib.import_module("fused_layer_norm_cuda")
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /usr/local/lib/python3.6/dist-packages/fused_layer_norm_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE
```

Here's my system information:
lsb_release -a
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```
Torch info:
```
>>> print(torch.__version__, torch.version.cuda)
1.6.0 10.2
```

nvcc --version
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
```

Any idea to solve it? Thanks!

**Comment by wutaiqiang** [comment]
https://github.com/NVIDIA/apex/issues/624
maybe it helps

**Comment by Jun-jie-Huang** [comment]
I think it's because BLINK uses `BertModel` in `pytorch-transformers`, which is an old version of `transformers`. The older version uses the `LayerNorm` in `apex`, and huggingface updates this in the new version (https://github.com/huggingface/transformers/issues/4703#issuecomment-636931781). I guess this causes the bug.

**Comment by Jun-jie-Huang** [comment]
> [NVIDIA/apex#624](https://github.com/NVIDIA/apex/issues/624)
> maybe it helps

I tried that, but it didn't work for me. Thx!

**Comment by Jun-jie-Huang** [comment]
Finally, I solved this problem by using the `pytorch_transformers==1.2.0` in the directory rather than installing it, so that I can mannually change the 
```
try:    
    from apex.normalization.fused_layer_norm import FusedLayerNorm as BertLayerNorm
except (ImportError, AttributeError) as e:    
    logger.info("Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .")    
    BertLayerNorm = torch.nn.LayerNorm
```
in `modeling_bert.py` to 
```
BertLayerNorm = torch.nn.LayerNorm
```
Just like the [this commit](https://github.com/huggingface/transformers/commit/98dd19b96b351f481e1268ab6c7b035bb21d106e). Then there may be some errors about path, but can be fixed through adding environment variables.

This is not a mainstream solution but it can work.
